### PR TITLE
German Fixes and Improvements

### PR DESCRIPTION
**Pull request by Max-Henning-Junghans**
I changed the capitalization of the personal pronouns in German to fit better.
Apart from that, I improved the translation of some tips.

### CODE REVIEW

**Comment by Max-Henning-Junghans** [comment]
@zedritsch I think I improved some little things about the translation, what do you think?

**Review by zedritsch — CHANGES_REQUESTED** [review]
Well, `OddTip1`, `OddTip7` and `OddTip9` are indeed better. But in German "dir" and "du" don't start with a capital letter. And the rest is either grammatically incorrect or doesn't respresent the original meaning. But you should keep the ones mentioned above. Also, would you mind adding #16's additional language buttons?
@Max-Henning-Junghans

**Comment by Max-Henning-Junghans** [comment]
@zedritsch Regarding starting with a capital letter, I learned it this way and looking at https://www.duden.de/sprachwissen/sprachratgeber/Gross-oder-Kleinschreibung-von-duDu-und-ihrIhr I would say both are right, as the game is directly speaking at the player, so "Allgemein gilt: In allen Textformen, in denen der Autor selbst den Leser persönlich anredet, kann man du/Du und die genannten Wörter großschreiben." fits.

Regarding `Tip16`: I saw multiple games where it was written as "Pausenmenü" not "Pausemenü". I cant really tell which one is grammatically correct, but I found no use of "Pausemenü"

Regarding `OddTip5`: For "deceased" I would say "verstorben" is both correct and fitting? 

Regarding `OddTip8`: I dont know this reference, I just googled it and found a marvel creature under that name and thought that the tip meant a singular creature

I will add the additional language buttons

**Comment by zedritsch** [comment]
It's in the first paragraph
> In der Regel werden die Formen des Anredepronomens _du_ kleingeschrieben, ebenso dann auch die der Mehrzahl _ihr_. [...]

`Tip16`: In the end, it doesn’t matter whether it’s singular or plural

`OddTip5`: Well, "deceased" refers to living beings, but nowadays hardly anyone distinguishes between them

`OddTip8`: I based my translation on the phenomenon of multi-headed creatures. However, it is very likely that `@``FinalForEach` meant this creature specifically

Additional Buttons: 👍🏻

I'll leave it up to you whether you keep these translations in. The only thing I strongly disagree with is the capitalization of the pronouns. Just because it is allowed in letters or something similar doesn't make me prefer it to the norm
@Max-Henning-Junghans

**Comment by Max-Henning-Junghans** [comment]
@zedritsch Was away this week, saw that you added my improvements meanwhile. Thanks for that :)

**Pull request closed without merging**
