### PR TITLE
(WIP) [TL_PH]: Update and Add Documentation

### PR DESCRIPTION
**Pull request by StartsMercury**
Though along with the changes is the initial partner documentation and I'm not certain if it is needed nor is final.

### CODE REVIEW

**Comment by FinalForEach** [comment]
This is good, but I won't merge it while it's a work in progress, I'm happy with the documentation as well.

**Comment by StartsMercury** [comment]
Thank you! Yes, it's still in working progress. I wanted to cover the existing translations as well. Also partly was waiting a comment about the documentation, hopefully this'll help future efforts.

**Comment by StartsMercury** [comment]
I'm slowly working on this, mostly on the phone. I haven't been able to get the time push the changes here.

**Comment by StartsMercury** [comment]
I'm unsure with the documentation format. I might reopen when I or someone figured a better format or procedure.

**Pull request closed without merging**
