### PR TITLE
Add Catalan

### PR DESCRIPTION
**Pull request by JoanRiosiPla**
Hi, I have translated the game to Catalan. Hope this helps bring the game to more people.

### CODE REVIEW

**Comment by FinalForEach** [comment]
Didn't know about this language, I learn something new every day. Can you add your name to the CREDITS.txt before I merge?

**Comment by JoanRiosiPla** [comment]
Sure! I'm on it. Also, Catalan is a language used in Catalonia, Valencia and the Balearic Islands (in Spain).

**Comment by lvllaby** [comment]
> Sure! I'm on it. Also, Catalan is a language used in Catalonia, Valencia and the Balearic Islands (in Spain).
Also in Andorra

**Comment by JoanRiosiPla** [comment]
Done!

**Pull request merged**
