### PR TITLE
Russian localisation

### PR DESCRIPTION
**Pull request by Svuvi**
Full russian localisation with tips and stuff
Dont beat me for borrowing Flux-Translations preAlphaText line, their version sounded a little better than what I wrote. The rest of translated lines overall match closely

### CODE REVIEW

**Comment by Dinozavvvr** [comment]
@Svuvi ты из ИТИС-а?)

**Comment by FinalForEach** [comment]
If you took the translation, and you are not the original author, I sadly cannot accept the MR. If you revert the latest commit however, I can accept it then; improvements can be made later if need be.

**Comment by Svuvi** [comment]
Sure, done

**Comment by Svuvi** [comment]
@Dinozavvvr нет, я учился в ДГТУ (не закончил и уехал из страны)

**Comment by FinalForEach** [comment]
Thank you! merging now

**Pull request merged**
