### PR TITLE
Fix issues in Ukrainian translation

### PR DESCRIPTION
**Pull request by danilwhale**
Used "better" translation for some texts and replaced `All Capitalized Text` with `Normal text`.

### CODE REVIEW

**Comment by FinalForEach** [comment]
Thanks, can you add your name to CREDITS.txt?

**Comment by FinalForEach** [comment]
Also if you could update the Tip15 to use $keybind_keyPickBlock like in the en_us.json that would be great

**Comment by danilwhale** [comment]
i forgor to add that this is ukrainian translation...

**Comment by FinalForEach** [comment]
Thank you, merging now

**Pull request merged**
