### PR TITLE
Made translation more organic and fixed some typos

### PR DESCRIPTION
**Pull request by notneat**
Apparently someone already made some changes before I could finish making my own, so probably some accentuation and spelling typos were already fixed

### CODE REVIEW

**Comment by FinalForEach** [comment]
If there are any changes that need to be made still, could you get the latest version and make another commit with your changes?

**Comment by notneat** [comment]
I think everything is up to date now

**Comment by FinalForEach** [comment]
One more thing, could you add your name to CREDITS.txt before I merge?

**Comment by notneat** [comment]
Here you go

**Comment by FinalForEach** [comment]
Thank you! Merging now.

**Pull request merged**
